const universalLoves = [
  "Golden Pumpkin",
  "Magic Rock Candy",
  "Pearl",
  "Prismatic Shard",
  "Rabbit's Foot",
];

const artisanGoods = [
  "Honey",
  "Wine",
  "Pale Ale",
  "Beer",
  "Mead",
  "Cheese",
  "Goat Cheese",
  "Coffee",
  "Green Tea",
  "Juice",
  "Cloth",
  "Mayonnaise",
  "Duck Mayonnaise",
  "Void Mayonnaise",
  "Dinosaur Mayonnaise",
  "Truffle Oil",
  "Oil",
  "Pickles",
  "Jelly",
  "Caviar",
  "Aged Roe",
];

const cooking = [
  "Fried Egg",
  "Omelet",
  "Salad",
  "Cheese Cauliflower",
  "Baked Fish",
  "Parnsip Soup",
  "Vegetable Medley",
  "Complete Breakfast",
  "Fried Calamari",
  "Strange Bun",
  "Lucky Lunch",
  "Fried Mushroom",
  "Pizza",
  "Bean Hotpot",
  "Glazed Yams",
  "Carp Surprise",
  "Hashbrowns",
  "Pancakes",
  "Salmon Dinner",
  "Fish Taco",
  "Crispy Bass",
  "Pepper Poppers",
  "Bread",
  "Tom Kha Soup",
  "Trout Soup",
  "Chocolate Cake",
  "Pick Cake",
  "Rhubarb Pie",
  "Cookie",
  "Spaghetti",
  "Fried Eel",
  "Spicy Eel",
  "Sashimi",
  "Maki Roll",
  "Tortilla",
  "Red Plate",
  "Eggplant Parmesan",
  "Rice Pudding",
  "Ice Cream",
  "Blueberry Tart",
  "Autumn's Bounty",
  "Pumpkin Soup",
  "Super Meal",
  "Cranberry Sauce",
  "Stuffing",
  "Farmer's Lunch",
  "Survival Burger",
  "Dish O' The Sea",
  "Miner's Treat",
  "Roots Platter",
  "Triple Shot Espresso",
  "Seafoam Pudding",
  "Algae Soup",
  "Pale Broth",
  "Plum Pudding",
  "Artichoke Dip",
  "Stir Fry",
  "Roasted Hazelnuts",
  "Pumpkin Pie",
  "Radish Salad",
  "Fruit Salad",
  "Blackberry Cobbler",
  "Cranberry Candy",
  "Bruschetta",
  "Coleslaw",
  "Fiddlehead Risotto",
  "Poppyseed Muffin",
  "Chowder",
  "Fish Stew",
  "Escargot",
  "Lobster Bisque",
  "Maple Bar",
  "Crab Cakes",
  "Shrimp Cocktail",
  "Ginger Ale",
  "Banana Pudding",
  "Mango Sticky Rice",
  "Poi",
  "Tropical Curry",
  "Squid Ink Ravioli",
];

const flowers = [
  "Sweet Pea",
  "Crocus",
  "Sunflower",
  "Tulip",
  "Summer Spangle",
  "Fairy Rose",
  "Blue Jazz",
  "Poppy",
];

const foragedMinerals = [
  "Quartz",
  "Earth Crystal",
  "Frozen Tear",
  "Fire Quartz",
];

const fruitTreeFruitsWithoutBananaMango = [
  "Apricot",
  "Cherry",
  "Orange",
  "Peach",
  "Apple",
  "Pomegranate",
];

const gems = [
  "Emerald",
  "Aquamarine",
  "Ruby",
  "Amethyst",
  "Topaz",
  "Jade",
  "Diamond",
  "Prismatic Shard",
];

const vegetables = [
  "Amaranth",
  "Artichoke",
  "Beet",
  "Bok Choy",
  "Cauliflower",
  "Corn",
  "Eggplant",
  "Fiddlehead Fern",
  "Garlic",
  "Green Bean",
  "Hops",
  "Kale",
  "Parsnip",
  "Potato",
  "Pumpkin",
  "Radish",
  "Red Cabbage",
  "Taro Root",
  "Tea Leaves",
  "Tomato",
  "Unmilled Rice",
  "Wheat",
  "Yam",
];

const eggs = [
  "Egg",
  "Large Egg",
  "Brown Egg",
  "Large Brown Egg",
  "Duck Egg",
  "Golden Egg",
  "Void Egg",
];

const fruits = [
  "Ancient Fruit",
  "Apple",
  "Apricot",
  "Banana",
  "Blackberry",
  "Blueberry",
  "Cactus Fruit",
  "Cherry",
  "Coconut",
  "Cranberries",
  "Crystal Fruit",
  "Grape",
  "Hot Pepper",
  "Mango",
  "Melon",
  "Orange",
  "Peach",
  "Pineapple",
  "Pomegranate",
  "Qi Fruit",
  "Rhubarb",
  "Salmonberry",
  "Spice Berry",
  "Starfruit",
  "Strawberry",
  "Wild Plum",
];

const fish = [
  "Pufferfish",
  "Anchovy",
  "Tuna",
  "Sardine",
  "Bream",
  "Largemouth Bas",
  "Smallmouth Bass",
  "Rainbow Trout",
  "Salmon",
  "Walleye",
  "Perch",
  "Carp",
  "Catfish",
  "Pike",
  "Sunfish",
  "Red Mullet",
  "Herring",
  "Eel",
  "Octupus",
  "Red Snapper",
  "Squid",
  "Sea Cucumber",
  "Super Cucumber",
  "Ghostfish",
  "Stonefish",
  "Ice Pip",
  "Lava Eel",
  "Sandfish",
  "Scorpion Carp",
  "Flounder",
  "Midnight Carp",
  "Sturgeon",
  "Tiger Trout",
  "Bullhead",
  "Tilapia",
  "Chub",
  "Dorado",
  "Albacore",
  "Shad",
  "Lingcod",
  "Halibut",
  "Woodskip",
  "Void Salmon",
  "Slimejack",
  "Stingray",
  "Lionfish",
  "Blue Discus",
  "Midnight Squid",
  "Spook Fish",
  "Blobfish",
  "Crimsonfish",
  "Angler",
  "Legend",
  "Glacierfish",
  "Mutant Carp",
  "Son of Crimsonfish",
  "Ms. Angler",
  "Legend II",
  "Glacierfish Jr.",
  "Lobster",
  "Clam",
  "Crayfish",
  "Crab",
  "Cockle",
  "Mussel",
  "Shrimp",
  "Snail",
  "Periwinkle",
];

const universalLikedExceptions = [
  // Artisan Goods
  "Oil",
  "Void Mayonnaise",
  // Cooking
  "Fried Egg",
  "Bread",
  "Strange Bun",
  "Seafoam Pudding",
  // Flowers
  "Poppy",
  // Foraged Minerals
  "Quartz",
  // Gems
  "Prismatic Shard",
  // Vegetables
  "Hops",
  "Tea Leaves",
  "Wheat",
];

const universalLikes = [
  ...artisanGoods,
  ...cooking,
  ...flowers,
  ...foragedMinerals,
  ...fruitTreeFruitsWithoutBananaMango,
  ...gems,
  ...vegetables,
].filter((gift) => {
  return !universalLikedExceptions.includes(gift);
});

const universalNeutrals = [
  "Bread",
  "Clam",
  "Coral",
  "Duck Feather",
  "Fried Egg",
  "Hops",
  "Nautilus Shell",
  "Rainbow Shell",
  "Roe",
  "Squid Ink",
  "Sweet Gem Berry",
  "Tea Leaves",
  "Truffle",
  "Wheat",
  "Wool",
];

export const giftPreferences = {
  Alex: {
    lovedGifts: [...universalLoves, "Complete Breakfast", "Salmon Dinner"],
    lovedExceptions: [],
    likedGifts: [...universalLikes, ...eggs],
    likedExceptions: ["Void Egg"],
    neutralGifts: [
      ...universalNeutrals,
      ...fruits,
      "Milk",
      "Large Milk",
      "Chanterelle",
      "Common Mushroom",
      "Daffodil",
      "Dandelion",
      "Ginger",
      "Hazelnut",
      "Leek",
      "Magma Cap",
      "Morel",
      "Purple Mushroom",
      "Snow Yam",
      "Winter Root",
    ],
    neutralExceptions: [...fruitTreeFruitsWithoutBananaMango, "Salmonberry"],
  },
  Elliot: {
    lovedGifts: [
      ...universalLoves,
      "Crab Cakes",
      "Duck Feather",
      "Lobster",
      "Pomegranate",
      "Squid Ink",
      "Tom Kha Soup",
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, ...fruits, "Octopus", "Squid"],
    likedExceptions: ["Amaranth", "Pizza", "Pomegranate", "Salmonberry"],
    neutralGifts: [...universalNeutrals, ...eggs, ...fish],
    neutralExceptions: [
      "Duck Feather",
      "Squid Ink",
      "Void Egg",
      "Carp",
      "Lobster",
      "Octopus",
      "Sea Cucumber",
      "Snail",
      "Squid",
    ],
  },
  Abigail: {
    lovedGifts: [
      ...universalLoves,
      "Amethyst",
      "Banana Pudding",
      "Blackberry Cobbler",
      "Chocolate Cake",
      "Pufferfish",
      "Pumpkin",
      "Spicy Eel",
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, "Quartz"],
    likedExceptions: [...vegetables],
    neutralGifts: [
      ...universalNeutrals,
      "Milk",
      "Large Milk",
      "Chanterelle",
      "Common Mushroom",
      "Daffodil",
      "Dandelion",
      "Ginger",
      "Hazelnut",
      "Leek",
      "Magma Cap",
      "Morel",
      "Purple Mushroom",
      "Snow Yam",
      "Winter Root",
    ],
    neutralExceptions: [],
  },
};
