import { PartialValueIndexer, ValueIndexer } from "../types";
import { Villagers } from "../villagers";

export enum Item {
  GoldenPumpkin = "Golden Pumpkin",
  MagicRockCandy = "Magic Rock Candy",
  Pearl = "Pearl",
  PrismaticShard = "Prismatic Shard",
  RabbitsFoot = "Rabbit's Foot",
  Honey = "Honey",
  Wine = "Wine",
  PaleAle = "Pale Ale",
  Beer = "Beer",
  Mead = "Mead",
  Cheese = "Cheese",
  GoatCheese = "Goat Cheese",
  Coffee = "Coffee",
  GreenTea = "Green Tea",
  Juice = "Juice",
  Cloth = "Cloth",
  Mayonnaise = "Mayonnaise",
  DuckMayonnaise = "Duck Mayonnaise",
  VoidMayonnaise = "Void Mayonnaise",
  DinosaurMayonnaise = "Dinosaur Mayonnaise",
  TruffleOil = "Truffle Oil",
  Oil = "Oil",
  Pickles = "Pickles",
  Jelly = "Jelly",
  Caviar = "Caviar",
  AgedRoe = "Aged Roe",
  FriedEgg = "Fried Egg",
  Omelet = "Omelet",
  Salad = "Salad",
  CheeseCauliflower = "Cheese Cauliflower",
  BakedFish = "Baked Fish",
  ParsnipSoup = "Parnsip Soup",
  VegetableMedley = "Vegetable Medley",
  CompleteBreakfast = "Complete Breakfast",
  FriedCalamari = "Fried Calamari",
  StrangeBun = "Strange Bun",
  LuckyLunch = "Lucky Lunch",
  FriedMushroom = "Fried Mushroom",
  Pizza = "Pizza",
  BeanHotpot = "Bean Hotpot",
  GlazedYams = "Glazed Yams",
  CarpSurprise = "Carp Surprise",
  Hashbrowns = "Hashbrowns",
  Pancakes = "Pancakes",
  SalmonDinner = "Salmon Dinner",
  FishTaco = "Fish Taco",
  CrispyBass = "Crispy Bass",
  PepperPoppers = "Pepper Poppers",
  Bread = "Bread",
  TomKhaSoup = "Tom Kha Soup",
  TroutSoup = "Trout Soup",
  ChocolateCake = "Chocolate Cake",
  PickCake = "Pick Cake",
  RhubarbPie = "Rhubarb Pie",
  Cookie = "Cookie",
  Spaghetti = "Spaghetti",
  FriedEel = "Fried Eel",
  SpicyEel = "Spicy Eel",
  Sashimi = "Sashimi",
  MakiRoll = "Maki Roll",
  Tortilla = "Tortilla",
  RedPlate = "Red Plate",
  EggplantParmesan = "Eggplant Parmesan",
  RicePudding = "Rice Pudding",
  IceCream = "Ice Cream",
  BlueberryTart = "Blueberry Tart",
  AutumnsBounty = "Autumn's Bounty",
  PumpkinSoup = "Pumpkin Soup",
  SuperMeal = "Super Meal",
  CranberrySauce = "Cranberry Sauce",
  Stuffing = "Stuffing",
  FarmersLunch = "Farmer's Lunch",
  SurvivalBurger = "Survival Burger",
  DishOTheSea = "Dish O' The Sea",
  MinersTreat = "Miner's Treat",
  RootsPlatter = "Roots Platter",
  TripleShotEspresso = "Triple Shot Espresso",
  SeafoamPudding = "Seafoam Pudding",
  AlgaeSoup = "Algae Soup",
  PaleBroth = "Pale Broth",
  PlumPudding = "Plum Pudding",
  ArtichokeDip = "Artichoke Dip",
  StirFry = "Stir Fry",
  RoastedHazelnuts = "Roasted Hazelnuts",
  PumpkinPie = "Pumpkin Pie",
  RadishSalad = "Radish Salad",
  FruitSalad = "Fruit Salad",
  BlackberryCobbler = "Blackberry Cobbler",
  CranberryCandy = "Cranberry Candy",
  Bruschetta = "Bruschetta",
  Coleslaw = "Coleslaw",
  FiddleheadRisotto = "Fiddlehead Risotto",
  PoppyseedMuffin = "Poppyseed Muffin",
  Chowder = "Chowder",
  FishStew = "Fish Stew",
  Escargot = "Escargot",
  LobsterBisque = "Lobster Bisque",
  MapleBar = "Maple Bar",
  CrabCakes = "Crab Cakes",
  ShrimpCocktail = "Shrimp Cocktail",
  GingerAle = "Ginger Ale",
  BananaPudding = "Banana Pudding",
  MangoStickyRice = "Mango Sticky Rice",
  Poi = "Poi",
  TropicalCurry = "Tropical Curry",
  SquidInkRavioli = "Squid Ink Ravioli",
  Egg = "Egg",
  LargeEgg = "Large Egg",
  BrownEgg = "Brown Egg",
  LargeBrownEgg = "Large Brown Egg",
  DuckEgg = "Duck Egg",
  GoldenEgg = "Golden Egg",
  VoidEgg = "Void Egg",
  SweetPea = "Sweet Pea",
  Crocus = "Crocus",
  Sunflower = "Sunflower",
  Tulip = "Tulip",
  SummerSpangle = "Summer Spangle",
  FairyRose = "Fairy Rose",
  BlueJazz = "Blue Jazz",
  Poppy = "Poppy",
  Quartz = "Quartz",
  EarthCrystal = "Earth Crystal",
  FrozenTear = "Frozen Tear",
  FireQuartz = "Fire Quartz",
  Apricot = "Apricot",
  Cherry = "Cherry",
  Orange = "Orange",
  Peach = "Peach",
  Apple = "Apple",
  Pomegranate = "Pomegranate",
  Emerald = "Emerald",
  Aquamarine = "Aquamarine",
  Ruby = "Ruby",
  Amethyst = "Amethyst",
  Topaz = "Topaz",
  Jade = "Jade",
  Diamond = "Diamond",
  Tigerseye = "Tigerseye",
  Opal = "Opal",
  FireOpal = "Fire Opal",
  Alamite = "Alamite",
  Bixite = "Bixite",
  Baryte = "Baryte",
  Aerinite = "Aerinite",
  Calcite = "Calcite",
  Dolomite = "Dolomite",
  Esperite = "Esperite",
  Fluorapatite = "Fluorapatite",
  Geminite = "Geminite",
  Helvite = "Helvite",
  Jamborite = "Jamborite",
  Jagoite = "Jagoite",
  Kyanite = "Kyanite",
  Lunarite = "Lunarite",
  Malachite = "Malachite",
  Neptunite = "Neptunite",
  LemonStone = "Lemon Stone",
  Nekoite = "Nekoite",
  Orpiment = "Orpiment",
  PetrifiedSlime = "Petrified Slime",
  ThunderEgg = "Thunder Egg",
  OceanStone = "Ocean Stone",
  Pyrite = "Pyrite",
  GhostCrystal = "Ghost Crystal",
  Jasper = "Jasper",
  Celestine = "Celestine",
  Marble = "Marble",
  Sandstone = "Sandstone",
  Granite = "Granite",
  Limestone = "Limestone",
  Soapstone = "Soapstone",
  Hematite = "Hematite",
  Mudstone = "Mudstone",
  Obsidian = "Obsidian",
  Slate = "Slate",
  FairyStone = "Fairy Stone",
  StarShards = "Star Shards",
  Amaranth = "Amaranth",
  Artichoke = "Artichoke",
  Beet = "Beet",
  BokChoy = "Bok Choy",
  Cauliflower = "Cauliflower",
  Corn = "Corn",
  Eggplant = "Eggplant",
  FiddleheadFern = "Fiddlehead Fern",
  Garlic = "Garlic",
  GreenBean = "Green Bean",
  Hops = "Hops",
  Kale = "Kale",
  Parsnip = "Parsnip",
  Potato = "Potato",
  Pumpkin = "Pumpkin",
  Radish = "Radish",
  RedCabbage = "Red Cabbage",
  TaroRoot = "Taro Root",
  TeaLeaves = "Tea Leaves",
  Tomato = "Tomato",
  UnmilledRice = "Unmilled Rice",
  Wheat = "Wheat",
  Yam = "Yam",
  AncientFruit = "Ancient Fruit",
  Banana = "Banana",
  Blackberry = "Blackberry",
  Blueberry = "Blueberry",
  CactusFruit = "Cactus Fruit",
  Coconut = "Coconut",
  Cranberries = "Cranberries",
  CrystalFruit = "Crystal Fruit",
  Grape = "Grape",
  HotPepper = "Hot Pepper",
  Mango = "Mango",
  Melon = "Melon",
  Pineapple = "Pineapple",
  QiFruit = "Qi Fruit",
  Rhubarb = "Rhubarb",
  Salmonberry = "Salmonberry",
  SpiceBerry = "Spice Berry",
  Starfruit = "Starfruit",
  Strawberry = "Strawberry",
  WildPlum = "Wild Plum",
  DwarfScrollI = "Dwarf Scroll I",
  DwarfScrollII = "Dwarf Scroll II",
  DwarfScrollIII = "Dwarf Scroll III",
  DwarfScrollIV = "Dwarf Scroll IV",
  ChippedAmphora = "Chipped Amphora",
  Arrowhead = "Arrowhead",
  AncientDoll = "Ancient Doll",
  ElvishJewelry = "Elvish Jewelry",
  ChewingStick = "Chewing Stick",
  OrnamentalFan = "Ornamental Fan",
  DinosaurEgg = "Dinosaur Egg",
  RareDisc = "Rare Disc",
  AncientSword = "Ancient Sword",
  RustySpoon = "Rusty Spoon",
  RustySpur = "Rusty Spur",
  ChickenStatue = "Chicken Statue",
  AncientSeed = "Ancient Seed",
  PrehistoricTool = "Prehistoric Tool",
  DriedStarfish = "Dried Starfish",
  Anchor = "Anchor",
  GlassShards = "Glass Shards",
  BoneFlute = "Bone Flute",
  PrehistoricHandaxe = "Prehistoric Handaxe",
  DwarvishHelm = "Dwarvish Helm",
  DwarfGadget = "Dwarf Gadget",
  AncientDrum = "Ancient Drum",
  GoldenMask = "Golden Mask",
  GoldenRelic = "Golden Relic",
  StrangeDoll = "Strange Doll",
  PrehistoricScapula = "Prehistoric Scapula",
  PrehistoricTibia = "Prehistoric Tibia",
  PrehistoricSkull = "Prehistoric Skull",
  SkeletalHand = "Skeletal Hand",
  PrehistoricRib = "Prehistoric Rib",
  PrehistoricVertebra = "Prehistoric Vertebra",
  SkeletalTail = "Skeletal Tail",
  NautilusFossil = "Nautilus Fossil",
  AmphibianFossil = "Amphibian Fossil",
  PalmFossil = "Palm Fossil",
  Trilobite = "Trilobite",
  Pufferfish = "Pufferfish",
  Anchovy = "Anchovy",
  Tuna = "Tuna",
  Sardine = "Sardine",
  Bream = "Bream",
  LargemouthBass = "Largemouth Bass",
  SmallmouthBass = "Smallmouth Bass",
  RainbowTrout = "Rainbow Trout",
  Salmon = "Salmon",
  Walleye = "Walleye",
  Perch = "Perch",
  Carp = "Carp",
  Catfish = "Catfish",
  Pike = "Pike",
  Sunfish = "Sunfish",
  RedMullet = "Red Mullet",
  Herring = "Herring",
  Eel = "Eel",
  Octopus = "Octupus",
  RedSnapper = "Red Snapper",
  Squid = "Squid",
  SeaCucumber = "Sea Cucumber",
  SuperCucumber = "Super Cucumber",
  Ghostfish = "Ghostfish",
  Stonefish = "Stonefish",
  IcePip = "Ice Pip",
  LavaEel = "Lava Eel",
  Sandfish = "Sandfish",
  ScorpionCarp = "Scorpion Carp",
  Flounder = "Flounder",
  MidnightCarp = "Midnight Carp",
  Sturgeon = "Sturgeon",
  TigerTrout = "Tiger Trout",
  Bullhead = "Bullhead",
  Tilapia = "Tilapia",
  Chub = "Chub",
  Dorado = "Dorado",
  Albacore = "Albacore",
  Shad = "Shad",
  Lingcod = "Lingcod",
  Halibut = "Halibut",
  Woodskip = "Woodskip",
  VoidSalmon = "Void Salmon",
  Slimejack = "Slimejack",
  Stingray = "Stingray",
  Lionfish = "Lionfish",
  BlueDiscus = "Blue Discus",
  MidnightSquid = "Midnight Squid",
  SpookFish = "Spook Fish",
  Blobfish = "Blobfish",
  Crimsonfish = "Crimsonfish",
  Angler = "Angler",
  Legend = "Legend",
  Glacierfish = "Glacierfish",
  MutantCarp = "Mutant Carp",
  SonOfCrimsonfish = "Son of Crimsonfish",
  MsAngler = "Ms. Angler",
  LegendII = "Legend II",
  GlacierfishJr = "Glacierfish Jr.",
  Lobster = "Lobster",
  Clam = "Clam",
  Crayfish = "Crayfish",
  Crab = "Crab",
  Cockle = "Cockle",
  Mussel = "Mussel",
  Shrimp = "Shrimp",
  Snail = "Snail",
  Perinwinkle = "Periwinkle",
  Coral = "Coral",
  DuckFeather = "Duck Feather",
  NautilusShell = "Nautilus Shell",
  RainbowShell = "Rainbow Shell",
  Roe = "Roe",
  SquidInk = "Squid Ink",
  SweetGemBerry = "Sweet Gem Berry",
  Truffle = "Truffle",
  Wool = "Wool",
  Milk = "Milk",
  LargeMilk = "Large Milk",
  Chanterelle = "Chanterelle",
  CommonMushroom = "Common Mushroom",
  Daffodil = "Daffodil",
  Dandelion = "Dandelion",
  Ginger = "Ginger",
  Hazelnut = "Hazelnut",
  Leek = "Leek",
  MagmaCap = "Magma Cap",
  Morel = "Morel",
  PurpleMushroom = "Purple Mushroom",
  SnowYam = "Snow Yam",
  WinterRoot = "Winter Root",
  SpringOnion = "Spring Onion",
  WildHorseradish = "Wild Horseradish",
  SolarEssence = "Solar Essence",
  VoidEssence = "Void Essence",
  GoldBar = "Gold Bar",
  IridiumBar = "Iridium Bar",
  OmniGeode = "Omni Geode",
  CopperBar = "Copper Bar",
  IronBar = "Iron Bar",
  Coal = "Coal",
  GoldOre = "Gold Ore",
  IridiumOre = "Iridium Ore",
  RefinedQuartz = "Refined Quartz",
  PinaColada = "Piña Colada",
  GoatMilk = "Goat Milk",
  LargeGoatMilk = "L. Goat Milk",
  CaveCarrot = "Cave Carrot",
  PinkCake = "Pink Cake",
  Holly = "Holly",
  Driftwood = "Driftwood",
  BatteryPack = "Battery Pack",
  RadioactiveBar = "Radioactive Bar",
  MapleSyrup = "Maple Syrup",
  OakResin = "Oak Resin",
  PineTar = "Pine Tar",
  RadioactiveOre = "Radioactive Ore",
  JojaCola = "Joja Cola",
  LifeElixir = "Life Elixir",
  OstrichEgg = "Ostrich Egg",
  DragonTooth = "Dragon Tooth",
  SeaUrchin = "Sea Urchin",
}

const universalLoves: Array<Item> = [
  Item.GoldenPumpkin,
  Item.MagicRockCandy,
  Item.Pearl,
  Item.PrismaticShard,
  Item.RabbitsFoot,
];

const artisanGoods: Array<Item> = [
  Item.Honey,
  Item.Wine,
  Item.PaleAle,
  Item.Beer,
  Item.Mead,
  Item.Cheese,
  Item.GoatCheese,
  Item.Coffee,
  Item.GreenTea,
  Item.Juice,
  Item.Cloth,
  Item.Mayonnaise,
  Item.DuckMayonnaise,
  Item.VoidMayonnaise,
  Item.DinosaurMayonnaise,
  Item.TruffleOil,
  Item.Oil,
  Item.Pickles,
  Item.Jelly,
  Item.Caviar,
  Item.AgedRoe,
  Item.MapleSyrup,
];

const cooking: Array<Item> = [
  Item.FriedEel,
  Item.Omelet,
  Item.Salad,
  Item.CheeseCauliflower,
  Item.BakedFish,
  Item.ParsnipSoup,
  Item.VegetableMedley,
  Item.CompleteBreakfast,
  Item.FriedCalamari,
  Item.StrangeBun,
  Item.LuckyLunch,
  Item.FriedMushroom,
  Item.Pizza,
  Item.BeanHotpot,
  Item.GlazedYams,
  Item.Hashbrowns,
  Item.Pancakes,
  Item.SalmonDinner,
  Item.FishTaco,
  Item.CrispyBass,
  Item.PepperPoppers,
  Item.Bread,
  Item.TomKhaSoup,
  Item.TroutSoup,
  Item.ChocolateCake,
  Item.PickCake,
  Item.RhubarbPie,
  Item.Cookie,
  Item.Spaghetti,
  Item.FriedEel,
  Item.SpicyEel,
  Item.Sashimi,
  Item.MakiRoll,
  Item.Tortilla,
  Item.RedPlate,
  Item.EggplantParmesan,
  Item.RicePudding,
  Item.IceCream,
  Item.BlueberryTart,
  Item.AutumnsBounty,
  Item.PumpkinSoup,
  Item.SuperMeal,
  Item.CranberrySauce,
  Item.Stuffing,
  Item.FarmersLunch,
  Item.SurvivalBurger,
  Item.DishOTheSea,
  Item.MinersTreat,
  Item.RootsPlatter,
  Item.TripleShotEspresso,
  Item.SeafoamPudding,
  Item.AlgaeSoup,
  Item.PaleBroth,
  Item.PlumPudding,
  Item.ArtichokeDip,
  Item.StirFry,
  Item.RoastedHazelnuts,
  Item.PumpkinPie,
  Item.RadishSalad,
  Item.FruitSalad,
  Item.BlackberryCobbler,
  Item.CranberryCandy,
  Item.Bruschetta,
  Item.Coleslaw,
  Item.FiddleheadRisotto,
  Item.PoppyseedMuffin,
  Item.Chowder,
  Item.FishStew,
  Item.Escargot,
  Item.LobsterBisque,
  Item.MapleBar,
  Item.CrabCakes,
  Item.ShrimpCocktail,
  Item.GingerAle,
  Item.BananaPudding,
  Item.MangoStickyRice,
  Item.Poi,
  Item.TropicalCurry,
  Item.SquidInkRavioli,
];

const flowers: Array<Item> = [
  Item.SweetPea,
  Item.Crocus,
  Item.Sunflower,
  Item.Tulip,
  Item.SummerSpangle,
  Item.FairyRose,
  Item.BlueJazz,
  Item.Poppy,
];

const foragedMinerals: Array<Item> = [
  Item.Quartz,
  Item.EarthCrystal,
  Item.FrozenTear,
  Item.FireQuartz,
];

const fruitTreeFruitsWithoutBananaMango: Array<Item> = [
  Item.Apricot,
  Item.Cherry,
  Item.Orange,
  Item.Peach,
  Item.Apple,
  Item.Pomegranate,
];

const gems: Array<Item> = [
  Item.Emerald,
  Item.Aquamarine,
  Item.Ruby,
  Item.Amethyst,
  Item.Topaz,
  Item.Jade,
  Item.Diamond,
  Item.PrismaticShard,
];

const geodeMinerals: Array<Item> = [
  Item.Tigerseye,
  Item.Opal,
  Item.FireOpal,
  Item.Alamite,
  Item.Bixite,
  Item.Baryte,
  Item.Aerinite,
  Item.Calcite,
  Item.Dolomite,
  Item.Esperite,
  Item.Fluorapatite,
  Item.Geminite,
  Item.Helvite,
  Item.Jamborite,
  Item.Jagoite,
  Item.Kyanite,
  Item.Lunarite,
  Item.Malachite,
  Item.Neptunite,
  Item.LemonStone,
  Item.Nekoite,
  Item.Orpiment,
  Item.PetrifiedSlime,
  Item.ThunderEgg,
  Item.OceanStone,
  Item.Pyrite,
  Item.GhostCrystal,
  Item.Jasper,
  Item.Celestine,
  Item.Marble,
  Item.Sandstone,
  Item.Granite,
  Item.Limestone,
  Item.Soapstone,
  Item.Hematite,
  Item.Mudstone,
  Item.Obsidian,
  Item.Slate,
  Item.FairyStone,
  Item.StarShards,
];

const vegetables: Array<Item> = [
  Item.Amaranth,
  Item.Artichoke,
  Item.Beet,
  Item.BokChoy,
  Item.Cauliflower,
  Item.Corn,
  Item.Eggplant,
  Item.FiddleheadFern,
  Item.Garlic,
  Item.GreenBean,
  Item.Hops,
  Item.Kale,
  Item.Parsnip,
  Item.Potato,
  Item.Pumpkin,
  Item.Radish,
  Item.RedCabbage,
  Item.TaroRoot,
  Item.TeaLeaves,
  Item.Tomato,
  Item.UnmilledRice,
  Item.Wheat,
  Item.Yam,
];

const eggs: Array<Item> = [
  Item.Egg,
  Item.LargeEgg,
  Item.BrownEgg,
  Item.LargeBrownEgg,
  Item.DuckEgg,
  Item.GoldenEgg,
  Item.VoidEgg,
];

const fruits: Array<Item> = [
  Item.AncientFruit,
  Item.Apple,
  Item.Apricot,
  Item.Banana,
  Item.Blackberry,
  Item.CactusFruit,
  Item.Cherry,
  Item.Coconut,
  Item.Cranberries,
  Item.CrystalFruit,
  Item.Grape,
  Item.HotPepper,
  Item.Mango,
  Item.Melon,
  Item.Orange,
  Item.Peach,
  Item.Pineapple,
  Item.Pomegranate,
  Item.QiFruit,
  Item.Rhubarb,
  Item.Salmonberry,
  Item.SpiceBerry,
  Item.Starfruit,
  Item.Strawberry,
  Item.WildPlum,
];

const milks: Array<Item> = [
  Item.Milk,
  Item.LargeMilk,
  Item.GoatMilk,
  Item.LargeGoatMilk,
];

const artifacts: Array<Item> = [
  Item.DwarfScrollI,
  Item.DwarfScrollII,
  Item.DwarfScrollIII,
  Item.DwarfScrollIV,
  Item.ChippedAmphora,
  Item.Arrowhead,
  Item.ElvishJewelry,
  Item.ChewingStick,
  Item.OrnamentalFan,
  Item.DinosaurEgg,
  Item.RareDisc,
  Item.AncientSword,
  Item.RustySpoon,
  Item.RustySpur,
  Item.ChickenStatue,
  Item.AncientSeed,
  Item.PrehistoricTool,
  Item.DriedStarfish,
  Item.Anchor,
  Item.GlassShards,
  Item.BoneFlute,
  Item.PrehistoricHandaxe,
  Item.DwarvishHelm,
  Item.DwarfGadget,
  Item.AncientDrum,
  Item.GoldenMask,
  Item.GoldenRelic,
  Item.StrangeDoll,
  Item.PrehistoricScapula,
  Item.PrehistoricTibia,
  Item.PrehistoricSkull,
  Item.SkeletalHand,
  Item.PrehistoricRib,
  Item.PrehistoricVertebra,
  Item.SkeletalTail,
  Item.NautilusFossil,
  Item.AmphibianFossil,
  Item.PalmFossil,
  Item.Trilobite,
];

const fish: Array<Item> = [
  Item.Pufferfish,
  Item.Anchovy,
  Item.Tuna,
  Item.Sardine,
  Item.Bream,
  Item.LargemouthBass,
  Item.SmallmouthBass,
  Item.RainbowTrout,
  Item.Salmon,
  Item.Walleye,
  Item.Perch,
  Item.Carp,
  Item.Catfish,
  Item.Pike,
  Item.Sunfish,
  Item.RedMullet,
  Item.Herring,
  Item.Eel,
  Item.Octopus,
  Item.RedSnapper,
  Item.Squid,
  Item.SeaCucumber,
  Item.SuperCucumber,
  Item.Ghostfish,
  Item.Stonefish,
  Item.IcePip,
  Item.LavaEel,
  Item.Sandfish,
  Item.ScorpionCarp,
  Item.Flounder,
  Item.MidnightCarp,
  Item.Sturgeon,
  Item.TigerTrout,
  Item.Bullhead,
  Item.Tilapia,
  Item.Chub,
  Item.Dorado,
  Item.Albacore,
  Item.Shad,
  Item.Lingcod,
  Item.Halibut,
  Item.Woodskip,
  Item.VoidSalmon,
  Item.Slimejack,
  Item.Stingray,
  Item.Lionfish,
  Item.BlueDiscus,
  Item.MidnightSquid,
  Item.SpookFish,
  Item.Blobfish,
  Item.Crimsonfish,
  Item.Angler,
  Item.Legend,
  Item.Glacierfish,
  Item.MutantCarp,
  Item.SonOfCrimsonfish,
  Item.MsAngler,
  Item.LegendII,
  Item.GlacierfishJr,
  Item.Lobster,
  Item.Clam,
  Item.Crayfish,
  Item.Crab,
  Item.Cockle,
  Item.Mussel,
  Item.Shrimp,
  Item.Snail,
  Item.Perinwinkle,
];

const universalLikedExceptions: Array<Item> = [
  // Artisan Goods
  Item.Oil,
  Item.VoidMayonnaise,
  // Cooking
  Item.FriedEgg,
  Item.Bread,
  Item.StrangeBun,
  Item.SeafoamPudding,
  // Flowers
  Item.Poppy,
  // Foraged Minerals
  Item.Quartz,
  // Gems
  Item.PrismaticShard,
  // Vegetables
  Item.Hops,
  Item.TeaLeaves,
  Item.Wheat,
];

const universalLikes: Array<Item> = [
  ...artisanGoods,
  ...cooking,
  ...flowers,
  ...foragedMinerals,
  ...fruitTreeFruitsWithoutBananaMango,
  ...gems,
  ...vegetables,
].filter((gift) => {
  return !universalLikedExceptions.includes(gift);
});

const universalNeutrals: Array<Item> = [
  Item.Bread,
  Item.Clam,
  Item.Coral,
  Item.DuckFeather,
  Item.FriedEgg,
  Item.Hops,
  Item.NautilusShell,
  Item.RainbowShell,
  Item.Roe,
  Item.SquidInk,
  Item.SweetGemBerry,
  Item.TeaLeaves,
  Item.Truffle,
  Item.Wheat,
  Item.Wool,
];

interface GiftPreference {
  lovedGifts: ReadonlyArray<Item>;
  lovedExceptions: ReadonlyArray<Item>;
  likedGifts: ReadonlyArray<Item>;
  likedGiftsOverride: ReadonlyArray<Item>;
  likedExceptions: ReadonlyArray<Item>;
  neutralGifts: ReadonlyArray<Item>;
  neutralExceptions: ReadonlyArray<Item>;
}

export const giftPreferences: ValueIndexer<Villagers, GiftPreference> = {
  Abigail: {
    lovedGifts: [
      ...universalLoves,
      Item.Amethyst,
      Item.BananaPudding,
      Item.BlackberryCobbler,
      Item.ChocolateCake,
      Item.Pufferfish,
      Item.Pumpkin,
      Item.SpicyEel,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, Item.Quartz],
    likedGiftsOverride: [],
    likedExceptions: [...vegetables],
    neutralGifts: [
      ...universalNeutrals,
      ...milks,
      Item.Chanterelle,
      Item.CommonMushroom,
      Item.Daffodil,
      Item.Dandelion,
      Item.Ginger,
      Item.Hazelnut,
      Item.Leek,
      Item.MagmaCap,
      Item.Morel,
      Item.PurpleMushroom,
      Item.SnowYam,
      Item.WinterRoot,
    ],
    neutralExceptions: [],
  },
  Alex: {
    lovedGifts: [...universalLoves, Item.CompleteBreakfast, Item.SalmonDinner],
    lovedExceptions: [],
    likedGifts: [...universalLikes, ...eggs],
    likedGiftsOverride: [],
    likedExceptions: [Item.VoidEgg],
    neutralGifts: [
      ...universalNeutrals,
      ...fruits,
      ...milks,
      Item.Chanterelle,
      Item.CommonMushroom,
      Item.Daffodil,
      Item.Ginger,
      Item.Hazelnut,
      Item.Leek,
      Item.MagmaCap,
      Item.Morel,
      Item.PurpleMushroom,
      Item.SnowYam,
      Item.WinterRoot,
    ],
    neutralExceptions: [...fruitTreeFruitsWithoutBananaMango, Item.Salmonberry],
  },
  Caroline: {
    lovedGifts: [
      ...universalLoves,
      Item.FishTaco,
      Item.GreenTea,
      Item.SummerSpangle,
      Item.TropicalCurry,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, Item.Daffodil, Item.TeaLeaves],
    likedGiftsOverride: [],
    likedExceptions: [Item.Amaranth, Item.DuckMayonnaise, Item.Mayonnaise],
    neutralGifts: [...universalNeutrals, ...eggs, ...fruits, ...milks],
    neutralExceptions: [
      Item.TeaLeaves,
      Item.VoidEgg,
      Item.Salmonberry,
      ...fruitTreeFruitsWithoutBananaMango,
    ],
  },
  Clint: {
    lovedGifts: [
      ...universalLoves,
      Item.Amethyst,
      Item.Aquamarine,
      Item.ArtichokeDip,
      Item.Emerald,
      Item.FiddleheadFern,
      Item.GoldBar,
      Item.IridiumBar,
      Item.Jade,
      Item.OmniGeode,
      Item.Ruby,
      Item.Topaz,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, Item.CopperBar, Item.IronBar],
    likedGiftsOverride: [],
    likedExceptions: [...flowers],
    neutralGifts: [
      ...universalNeutrals,
      ...eggs,
      ...fruits,
      ...milks,
      Item.Chanterelle,
      Item.CommonMushroom,
      Item.Coal,
      Item.Daffodil,
      Item.Dandelion,
      Item.Ginger,
      Item.GoldOre,
      Item.Hazelnut,
      Item.IridiumOre,
      Item.Leek,
      Item.MagmaCap,
      Item.Morel,
      Item.PurpleMushroom,
      Item.RefinedQuartz,
      Item.SnowYam,
      Item.WinterRoot,
    ],
    neutralExceptions: [
      Item.VoidEgg,
      ...fruitTreeFruitsWithoutBananaMango,
      Item.Salmonberry,
    ],
  },
  Demetrius: {
    lovedGifts: [
      ...universalLoves,
      Item.BeanHotpot,
      Item.IceCream,
      Item.RicePudding,
      Item.Strawberry,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, ...eggs, ...fruits, Item.PurpleMushroom],
    likedGiftsOverride: [],
    likedExceptions: [Item.VoidEgg, Item.Strawberry],
    neutralGifts: [
      ...universalNeutrals,
      ...fish,
      Item.Chanterelle,
      Item.CommonMushroom,
      Item.Daffodil,
      Item.Dandelion,
      Item.Ginger,
      Item.Hazelnut,
      Item.Leek,
      Item.MagmaCap,
      Item.Morel,
      Item.SnowYam,
      Item.WildHorseradish,
      Item.WinterRoot,
    ],
    neutralExceptions: [Item.Carp, Item.Snail],
  },
  Dwarf: {
    lovedGifts: [
      ...universalLoves,
      Item.Amethyst,
      Item.Aquamarine,
      Item.Emerald,
      Item.Jade,
      Item.LemonStone,
      Item.OmniGeode,
      Item.Ruby,
      Item.Topaz,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, ...artifacts, Item.CaveCarrot, Item.Quartz],
    likedGiftsOverride: [],
    likedExceptions: [],
    neutralGifts: [
      ...universalNeutrals,
      ...fruits,
      Item.SolarEssence,
      Item.VoidEssence,
    ],
    neutralExceptions: [...fruitTreeFruitsWithoutBananaMango, Item.Salmonberry],
  },
  Elliott: {
    lovedGifts: [
      ...universalLoves,
      Item.CrabCakes,
      Item.DuckFeather,
      Item.Lobster,
      Item.Pomegranate,
      Item.SquidInk,
      Item.TomKhaSoup,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, ...fruits, Item.Octopus, Item.Squid],
    likedGiftsOverride: [],
    likedExceptions: [
      Item.Amaranth,
      Item.Pizza,
      Item.Pomegranate,
      Item.Salmonberry,
    ],
    neutralGifts: [...universalNeutrals, ...eggs, ...fish],
    neutralExceptions: [
      Item.DuckFeather,
      Item.SquidInk,
      Item.VoidEgg,
      Item.Carp,
      Item.Lobster,
      Item.Octopus,
      Item.SeaCucumber,
      Item.Snail,
      Item.Squid,
    ],
  },
  Emily: {
    lovedGifts: [
      ...universalLoves,
      Item.Amethyst,
      Item.Aquamarine,
      Item.Cloth,
      Item.Emerald,
      Item.Jade,
      Item.Ruby,
      Item.SurvivalBurger,
      Item.Topaz,
      Item.Wool,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, Item.Daffodil, Item.Quartz],
    likedGiftsOverride: [],
    likedExceptions: [
      Item.FishTaco,
      Item.FriedEel,
      Item.IceCream,
      Item.MakiRoll,
      Item.RicePudding,
      Item.SalmonDinner,
      Item.SpicyEel,
      Item.Sashimi,
    ],
    neutralGifts: [
      ...universalNeutrals,
      ...eggs,
      ...fruits,
      ...milks,
      Item.Chanterelle,
      Item.CommonMushroom,
      Item.Dandelion,
      Item.Ginger,
      Item.Hazelnut,
      Item.Leek,
      Item.MagmaCap,
      Item.Morel,
      Item.PurpleMushroom,
      Item.SnowYam,
      Item.WildHorseradish,
      Item.WinterRoot,
    ],
    neutralExceptions: [
      Item.Wool,
      Item.VoidEgg,
      ...fruitTreeFruitsWithoutBananaMango,
      Item.Salmonberry,
    ],
  },
  Evelyn: {
    lovedGifts: [
      ...universalLoves,
      Item.Beet,
      Item.ChocolateCake,
      Item.Diamond,
      Item.FairyRose,
      Item.Stuffing,
      Item.Tulip,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, ...milks, Item.Daffodil],
    likedGiftsOverride: [],
    likedExceptions: [
      Item.FriedEel,
      Item.Garlic,
      Item.MakiRoll,
      Item.Sashimi,
      Item.SpicyEel,
      Item.TroutSoup,
    ],
    neutralGifts: [
      ...universalNeutrals,
      ...eggs,
      ...fruits,
      Item.Chanterelle,
      Item.CommonMushroom,
      Item.Dandelion,
      Item.Ginger,
      Item.Hazelnut,
      Item.Leek,
      Item.MagmaCap,
      Item.Morel,
      Item.PurpleMushroom,
      Item.SnowYam,
      Item.WinterRoot,
    ],
    neutralExceptions: [
      ...fruitTreeFruitsWithoutBananaMango,
      Item.Clam,
      Item.Coral,
      Item.VoidEgg,
      Item.Salmonberry,
      Item.SpiceBerry,
    ],
  },
  George: {
    lovedGifts: [...universalLoves, Item.FriedMushroom, Item.Leek],
    lovedExceptions: [],
    likedGifts: [...universalLikes, Item.Daffodil],
    likedGiftsOverride: [],
    likedExceptions: [...flowers],
    neutralGifts: [
      ...universalNeutrals,
      ...eggs,
      ...fruits,
      ...milks,
      Item.Chanterelle,
      Item.CommonMushroom,
      Item.Ginger,
      Item.Hazelnut,
      Item.MagmaCap,
      Item.Morel,
      Item.PurpleMushroom,
      Item.SnowYam,
      Item.WinterRoot,
    ],
    neutralExceptions: [
      Item.VoidEgg,
      ...fruitTreeFruitsWithoutBananaMango,
      Item.Salmonberry,
    ],
  },
  Gus: {
    lovedGifts: [
      ...universalLoves,
      Item.Diamond,
      Item.Escargot,
      Item.FishTaco,
      Item.Orange,
      Item.TropicalCurry,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, Item.Daffodil],
    likedGiftsOverride: [],
    likedExceptions: [Item.Coleslaw],
    neutralGifts: [...universalNeutrals, ...eggs, ...fruits, ...milks],
    neutralExceptions: [
      Item.VoidEgg,
      ...fruitTreeFruitsWithoutBananaMango,
      Item.Salmonberry,
      Item.Chanterelle,
      Item.CommonMushroom,
      Item.Dandelion,
      Item.Ginger,
      Item.Hazelnut,
      Item.Leek,
      Item.MagmaCap,
      Item.Morel,
      Item.PurpleMushroom,
      Item.SnowYam,
      Item.WinterRoot,
    ],
  },
  Haley: {
    lovedGifts: [
      ...universalLoves,
      Item.Coconut,
      Item.FruitSalad,
      Item.PinkCake,
      Item.Sunflower,
    ],
    lovedExceptions: [Item.PrismaticShard],
    likedGifts: [...universalLikes, Item.Daffodil],
    likedGiftsOverride: [],
    likedExceptions: [...vegetables],
    neutralGifts: [...universalNeutrals],
    neutralExceptions: [],
  },
  Harvey: {
    lovedGifts: [
      ...universalLoves,
      Item.Coffee,
      Item.Pickles,
      Item.SuperMeal,
      Item.TruffleOil,
      Item.Wine,
    ],
    lovedExceptions: [],
    likedGifts: [
      ...universalLikes,
      ...fruits,
      Item.Chanterelle,
      Item.CommonMushroom,
      Item.Daffodil,
      Item.Dandelion,
      Item.DuckEgg,
      Item.DuckFeather,
      Item.Ginger,
      Item.GoatMilk,
      Item.Hazelnut,
      Item.Holly,
      Item.LargeGoatMilk,
      Item.Leek,
      Item.MagmaCap,
      Item.Morel,
      Item.PurpleMushroom,
      Item.Quartz,
      Item.SnowYam,
      Item.SpringOnion,
      Item.WildHorseradish,
      Item.WinterRoot,
    ],
    likedGiftsOverride: [],
    likedExceptions: [
      Item.Cheese,
      Item.GoatCheese,
      Item.BlueberryTart,
      Item.ChocolateCake,
      Item.Cookie,
      Item.CranberrySauce,
      Item.FriedMushroom,
      Item.GlazedYams,
      Item.Hashbrowns,
      Item.IceCream,
      Item.Pancakes,
      Item.PinkCake,
      Item.Pizza,
      Item.RhubarbPie,
      Item.RicePudding,
      Item.Salmonberry,
      Item.SpiceBerry,
    ],
    neutralGifts: [...universalNeutrals, ...eggs],
    neutralExceptions: [
      Item.DuckFeather,
      Item.Bread,
      Item.Coral,
      Item.NautilusShell,
      Item.RainbowShell,
      Item.DuckEgg,
      Item.VoidEgg,
    ],
  },
  Jas: {
    lovedGifts: [
      ...universalLoves,
      Item.FairyRose,
      Item.PinkCake,
      Item.PlumPudding,
    ],
    lovedExceptions: [],
    likedGifts: [
      ...universalLikes,
      Item.Honey,
      Item.Jelly,
      Item.Oil,
      Item.Coconut,
      Item.Daffodil,
    ],
    likedGiftsOverride: [Item.Honey, Item.Jelly, Item.Oil],
    likedExceptions: [Item.TripleShotEspresso, ...vegetables, ...artisanGoods],
    neutralGifts: [...universalNeutrals, ...milks],
    neutralExceptions: [],
  },
  Jodi: {
    lovedGifts: [
      ...universalLoves,
      Item.ChocolateCake,
      Item.CrispyBass,
      Item.Diamond,
      Item.EggplantParmesan,
      Item.FriedEel,
      Item.Pancakes,
      Item.RhubarbPie,
      Item.VegetableMedley,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, ...eggs, ...fruits, ...milks],
    likedGiftsOverride: [],
    likedExceptions: [Item.Garlic, Item.VoidEgg, Item.SpiceBerry],
    neutralGifts: [...universalNeutrals],
    neutralExceptions: [],
  },
  Leah: {
    lovedGifts: [
      ...universalLoves,
      Item.GoatCheese,
      Item.PoppyseedMuffin,
      Item.Salad,
      Item.StirFry,
      Item.Truffle,
      Item.VegetableMedley,
      Item.Wine,
    ],
    lovedExceptions: [],
    likedGifts: [
      ...universalLikes,
      ...eggs,
      ...fruits,
      ...milks,
      Item.Chanterelle,
      Item.CommonMushroom,
      Item.Daffodil,
      Item.Dandelion,
      Item.Driftwood,
      Item.Ginger,
      Item.Hazelnut,
      Item.Holly,
      Item.Leek,
      Item.MagmaCap,
      Item.Morel,
      Item.PurpleMushroom,
      Item.SnowYam,
      Item.SpringOnion,
      Item.WildHorseradish,
      Item.WinterRoot,
    ],
    likedGiftsOverride: [Item.EarthCrystal, Item.Diamond],
    likedExceptions: [
      ...foragedMinerals,
      ...gems,
      Item.CarpSurprise,
      Item.Cookie,
      Item.Hashbrowns,
      Item.IceCream,
      Item.Pancakes,
      Item.PinkCake,
      Item.Pizza,
      Item.RicePudding,
      Item.SurvivalBurger,
      Item.Tortilla,
      Item.VoidEgg,
    ],
    neutralGifts: [...universalNeutrals],
    neutralExceptions: [],
  },
  Lewis: {
    lovedGifts: [
      ...universalLoves,
      Item.AutumnsBounty,
      Item.GlazedYams,
      Item.GreenTea,
      Item.HotPepper,
      Item.VegetableMedley,
    ],
    lovedExceptions: [],
    likedGifts: [
      ...universalLikes,
      Item.Blueberry,
      Item.CactusFruit,
      Item.Coconut,
    ],
    likedGiftsOverride: [],
    likedExceptions: [],
    neutralGifts: [...universalNeutrals, ...eggs, ...fruits],
    neutralExceptions: [
      Item.VoidEgg,
      ...fruitTreeFruitsWithoutBananaMango,
      Item.Blueberry,
      Item.CactusFruit,
      Item.Coconut,
      Item.HotPepper,
      Item.Salmonberry,
    ],
  },
  Linus: {
    lovedGifts: [
      ...universalLoves,
      Item.BlueberryTart,
      Item.CactusFruit,
      Item.Coconut,
      Item.DishOTheSea,
      Item.Yam,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, ...eggs, ...milks, ...fruits],
    likedGiftsOverride: [Item.Diamond],
    likedExceptions: [
      ...foragedMinerals,
      ...gems,
      Item.VoidEgg,
      Item.CactusFruit,
      Item.Coconut,
      Item.Chanterelle,
      Item.CommonMushroom,
      Item.Daffodil,
      Item.Dandelion,
      Item.Ginger,
      Item.Hazelnut,
      Item.Leek,
      Item.MagmaCap,
      Item.Morel,
      Item.PurpleMushroom,
      Item.SnowYam,
      Item.SpringOnion,
      Item.WildHorseradish,
      Item.WinterRoot,
    ],
    neutralGifts: [...universalNeutrals, ...fish],
    neutralExceptions: [Item.Carp, Item.Snail],
  },
  Marnie: {
    lovedGifts: [
      ...universalLoves,
      Item.Diamond,
      Item.FarmersLunch,
      Item.PinkCake,
      Item.PumpkinPie,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, ...eggs, ...milks, Item.Quartz],
    likedGiftsOverride: [],
    likedExceptions: [Item.VoidEgg],
    neutralGifts: [
      ...universalNeutrals,
      ...fruits,
      Item.Chanterelle,
      Item.CommonMushroom,
      Item.Daffodil,
      Item.Dandelion,
      Item.Ginger,
      Item.Hazelnut,
      Item.Leek,
      Item.MagmaCap,
      Item.Morel,
      Item.PurpleMushroom,
      Item.SnowYam,
      Item.WinterRoot,
    ],
    neutralExceptions: [...fruitTreeFruitsWithoutBananaMango, Item.Salmonberry],
  },
  Maru: {
    lovedGifts: [
      ...universalLoves,
      Item.BatteryPack,
      Item.Cauliflower,
      Item.CheeseCauliflower,
      Item.Diamond,
      Item.GoldBar,
      Item.IridiumBar,
      Item.MinersTreat,
      Item.PepperPoppers,
      Item.RadioactiveBar,
      Item.RhubarbPie,
      Item.Strawberry,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes],
    likedGiftsOverride: [],
    likedExceptions: [
      Item.Honey,
      Item.MapleSyrup,
      Item.Pickles,
      Item.CopperBar,
      Item.IronBar,
      Item.OakResin,
      Item.PineTar,
      Item.Quartz,
      Item.RadioactiveOre,
    ],
    neutralGifts: [
      ...universalNeutrals,
      ...eggs,
      ...fruits,
      ...milks,
      Item.Chanterelle,
      Item.Daffodil,
      Item.Dandelion,
      Item.Ginger,
      Item.Hazelnut,
      Item.Leek,
      Item.MagmaCap,
      Item.Morel,
      Item.PurpleMushroom,
      Item.WildHorseradish,
      Item.WinterRoot,
    ],
    neutralExceptions: [
      Item.Truffle,
      Item.VoidEgg,
      Item.Blackberry,
      Item.CrystalFruit,
      ...fruitTreeFruitsWithoutBananaMango,
      Item.Salmonberry,
      Item.Strawberry,
    ],
  },
  Pam: {
    lovedGifts: [
      ...universalLoves,
      Item.Beer,
      Item.CactusFruit,
      Item.GlazedYams,
      Item.Mead,
      Item.PaleAle,
      Item.Parsnip,
      Item.ParsnipSoup,
      Item.PinaColada,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, ...fruits, ...milks, Item.Daffodil],
    likedGiftsOverride: [],
    likedExceptions: [Item.CactusFruit],
    neutralGifts: [
      ...universalNeutrals,
      ...fish,
      Item.Chanterelle,
      Item.CommonMushroom,
      Item.Dandelion,
      Item.Ginger,
      Item.Hazelnut,
      Item.Leek,
      Item.MagmaCap,
      Item.Morel,
      Item.PurpleMushroom,
      Item.SnowYam,
      Item.WinterRoot,
    ],
    neutralExceptions: [Item.Carp, Item.Octopus, Item.Snail, Item.Squid],
  },

  Penny: {
    lovedGifts: [
      ...universalLoves,
      Item.Diamond,
      Item.Emerald,
      Item.Melon,
      Item.Poppy,
      Item.PoppyseedMuffin,
      Item.RedPlate,
      Item.RootsPlatter,
      Item.Sandfish,
      Item.TomKhaSoup,
    ],
    lovedExceptions: [Item.RabbitsFoot],
    likedGifts: [
      ...universalLikes,
      ...milks,
      Item.Dandelion,
      Item.Leek,
      ...artifacts,
    ],
    likedGiftsOverride: [],
    likedExceptions: [
      Item.AlgaeSoup,
      Item.Beer,
      Item.Mead,
      Item.PaleAle,
      Item.PaleBroth,
      Item.PinaColada,
      Item.TomKhaSoup,
      Item.Wine,
    ],
    neutralGifts: [
      ...universalNeutrals,
      ...eggs,
      ...fruits,
      Item.Chanterelle,
      Item.CommonMushroom,
      Item.Daffodil,
      Item.Ginger,
      Item.Hazelnut,
      Item.MagmaCap,
      Item.Morel,
      Item.SnowYam,
      Item.WildHorseradish,
      Item.WinterRoot,
    ],
    neutralExceptions: [
      Item.DuckFeather,
      Item.Hops,
      Item.Wool,
      Item.VoidEgg,
      Item.Grape,
      Item.Melon,
      Item.Salmonberry,
      ...fruitTreeFruitsWithoutBananaMango,
    ],
  },
  Pierre: {
    lovedGifts: [...universalLoves, Item.FriedCalamari],
    lovedExceptions: [],
    likedGifts: [
      ...universalLikes,
      Item.Daffodil,
      Item.Dandelion,
      ...eggs,
      ...milks,
    ],
    likedGiftsOverride: [Item.Diamond],
    likedExceptions: [
      Item.VoidEgg,
      Item.Corn,
      Item.Garlic,
      ...foragedMinerals,
      ...gems,
      Item.ParsnipSoup,
      Item.Tortilla,
    ],
    neutralGifts: [...universalNeutrals, ...fruits],
    neutralExceptions: [...fruitTreeFruitsWithoutBananaMango, Item.Salmonberry],
  },
  Robin: {
    lovedGifts: [
      ...universalLoves,
      Item.GoatCheese,
      Item.Peach,
      Item.Spaghetti,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, ...milks, ...fruits],
    likedGiftsOverride: [],
    likedExceptions: [Item.Peach],
    neutralGifts: [...universalNeutrals, ...eggs],
    neutralExceptions: [Item.VoidEgg],
  },
  Sam: {
    lovedGifts: [
      ...universalLoves,
      Item.CactusFruit,
      Item.MapleBar,
      Item.Pizza,
      Item.Tigerseye,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, Item.JojaCola, ...eggs],
    likedGiftsOverride: [],
    likedExceptions: [
      Item.VoidEgg,
      Item.DuckMayonnaise,
      Item.Mayonnaise,
      Item.Pickles,
      ...vegetables,
    ],
    neutralGifts: [...universalNeutrals, ...fruits, ...milks],
    neutralExceptions: [
      ...fruitTreeFruitsWithoutBananaMango,
      Item.CactusFruit,
      Item.Salmonberry,
    ],
  },
  Sebastian: {
    lovedGifts: [
      ...universalLoves,
      Item.FrozenTear,
      Item.Obsidian,
      Item.PumpkinSoup,
      Item.Sashimi,
      Item.VoidEgg,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, Item.Flounder, Item.Quartz],
    likedGiftsOverride: [Item.Coffee, Item.GreenTea, Item.Oil],
    likedExceptions: [
      ...flowers,
      Item.CompleteBreakfast,
      Item.FarmersLunch,
      Item.Omelet,
      ...artisanGoods,
    ],
    neutralGifts: [...universalNeutrals, ...fruits, ...fish, ...milks],
    neutralExceptions: [
      ...fruitTreeFruitsWithoutBananaMango,
      Item.Salmonberry,
      Item.Carp,
      Item.Flounder,
      Item.Snail,
    ],
  },
  Shane: {
    lovedGifts: [
      ...universalLoves,
      Item.Beer,
      Item.HotPepper,
      Item.PepperPoppers,
      Item.Pizza,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, ...eggs, ...fruits],
    likedGiftsOverride: [],
    likedExceptions: [Item.Pickles, Item.VoidEgg, Item.HotPepper],
    neutralGifts: [...universalNeutrals, ...milks],
    neutralExceptions: [],
  },
  Vincent: {
    lovedGifts: [
      ...universalLoves,
      Item.CranberryCandy,
      Item.GingerAle,
      Item.Grape,
      Item.PinkCake,
      Item.Snail,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, Item.Coconut, Item.Daffodil],
    likedGiftsOverride: [Item.Honey, Item.Jelly, Item.Oil],
    likedExceptions: [Item.TripleShotEspresso, ...vegetables, ...artisanGoods],
    neutralGifts: [...universalNeutrals, ...milks],
    neutralExceptions: [],
  },
  Willy: {
    lovedGifts: [
      ...universalLoves,
      Item.Catfish,
      Item.Diamond,
      Item.IridiumBar,
      Item.Mead,
      Item.Octopus,
      Item.Pumpkin,
      Item.SeaCucumber,
      Item.Sturgeon,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes],
    likedGiftsOverride: [
      Item.GoldBar,
      Item.Quartz,
      Item.Lingcod,
      Item.TigerTrout,
      Item.BakedFish,
      Item.CarpSurprise,
      Item.Chowder,
      Item.CrabCakes,
      Item.CrispyBass,
      Item.FishStew,
      Item.FishTaco,
      Item.FriedCalamari,
      Item.FriedEel,
      Item.LobsterBisque,
      Item.SalmonDinner,
      Item.SeafoamPudding,
      Item.TroutSoup,
    ],
    likedExceptions: [Item.LifeElixir, ...cooking],
    neutralGifts: [
      ...universalNeutrals,
      ...eggs,
      ...fish,
      ...fruits,
      ...milks,
      Item.DishOTheSea,
      Item.MakiRoll,
      Item.Sashimi,
    ],
    neutralExceptions: [
      Item.VoidEgg,
      Item.Carp,
      Item.Catfish,
      Item.Lingcod,
      Item.Octopus,
      Item.SeaCucumber,
      Item.Snail,
      Item.Sturgeon,
      Item.TigerTrout,
      ...fruitTreeFruitsWithoutBananaMango,
      Item.Salmonberry,
    ],
  },
  Wizard: {
    lovedGifts: [
      ...universalLoves,
      Item.PurpleMushroom,
      Item.SolarEssence,
      Item.SuperCucumber,
      Item.VoidEssence,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, ...geodeMinerals, Item.Quartz],
    likedGiftsOverride: [],
    likedExceptions: [],
    neutralGifts: [...universalNeutrals, ...fruits],
    neutralExceptions: [...fruitTreeFruitsWithoutBananaMango, Item.Salmonberry],
  },
  Sandy: {
    lovedGifts: [
      ...universalLoves,
      Item.Crocus,
      Item.Daffodil,
      Item.MangoStickyRice,
      Item.SweetPea,
    ],
    lovedExceptions: [],
    likedGifts: [
      ...universalLikes,
      ...fruits,
      Item.GoatMilk,
      Item.LargeGoatMilk,
      Item.Quartz,
      Item.Wool,
    ],
    likedGiftsOverride: [],
    likedExceptions: [],
    neutralGifts: [
      ...universalNeutrals,
      ...eggs,
      Item.Chanterelle,
      Item.CommonMushroom,
      Item.Dandelion,
      Item.Ginger,
      Item.Hazelnut,
      Item.LargeMilk,
      Item.Leek,
      Item.MagmaCap,
      Item.Milk,
      Item.Morel,
      Item.PurpleMushroom,
      Item.SnowYam,
      Item.WildHorseradish,
      Item.WinterRoot,
    ],
    neutralExceptions: [Item.Wool, Item.VoidEgg],
  },
  Kent: {
    lovedGifts: [
      ...universalLoves,
      Item.FiddleheadRisotto,
      Item.RoastedHazelnuts,
    ],
    lovedExceptions: [],
    likedGifts: [...universalLikes, ...eggs, ...fruits, Item.Daffodil],
    likedGiftsOverride: [],
    likedExceptions: [
      Item.AlgaeSoup,
      Item.Sashimi,
      Item.Tortilla,
      Item.VoidEgg,
    ],
    neutralGifts: [
      ...universalNeutrals,
      Item.Chanterelle,
      Item.CommonMushroom,
      Item.Dandelion,
      Item.Ginger,
      Item.Hazelnut,
      Item.Leek,
      Item.MagmaCap,
      Item.Morel,
      Item.PurpleMushroom,
      Item.WildHorseradish,
      Item.WinterRoot,
    ],
    neutralExceptions: [],
  },
  Krobus: {
    lovedGifts: [
      ...universalLoves,
      Item.Diamond,
      Item.IridiumBar,
      Item.Pumpkin,
      Item.VoidEgg,
      Item.VoidMayonnaise,
      Item.WildHorseradish,
    ],
    lovedExceptions: [],
    likedGifts: [
      ...universalLikes,
      Item.GoldBar,
      Item.Quartz,
      Item.SeafoamPudding,
    ],
    likedGiftsOverride: [],
    likedExceptions: [Item.LifeElixir, ...cooking],
    neutralGifts: [...universalNeutrals, ...eggs, ...fruits, ...milks],
    neutralExceptions: [
      ...fruitTreeFruitsWithoutBananaMango,
      Item.Salmonberry,
      Item.VoidEgg,
    ],
  },
  Leo: {
    lovedGifts: [
      ...universalLoves,
      Item.DuckFeather,
      Item.Mango,
      Item.OstrichEgg,
      Item.Poi,
    ],
    lovedExceptions: [],
    likedGifts: [
      ...universalLikes,
      Item.DragonTooth,
      Item.NautilusShell,
      Item.Quartz,
      Item.RainbowShell,
      Item.SeaUrchin,
      Item.SpiceBerry,
    ],
    likedGiftsOverride: [Item.MangoStickyRice],
    likedExceptions: [
      Item.Beer,
      Item.Coffee,
      Item.LifeElixir,
      Item.Mead,
      Item.PaleAle,
      Item.Pickles,
      Item.PinaColada,
      Item.Wine,
      ...cooking,
    ],
    neutralGifts: [
      ...universalNeutrals,
      ...eggs,
      ...fish,
      ...fruits,
      ...milks,
      Item.Coffee,
    ],
    neutralExceptions: [
      Item.DuckFeather,
      Item.Hops,
      Item.NautilusShell,
      Item.RainbowShell,
      Item.OstrichEgg,
      Item.VoidEgg,
      Item.Carp,
      Item.Snail,
      ...fruitTreeFruitsWithoutBananaMango,
      Item.Mango,
      Item.Salmonberry,
      Item.SpiceBerry,
    ],
  },
};
